
# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "paru -S --needed"
remove = "paru -Rns"
sync = "paru -Syy --needed"
upgrade = "paru -Syyu --needed"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

plural_name = "system packages"

hook_name = "system_packages"

[config]
many_args = true

